### ISSUE TITLE
emailjs: module issues with "no form of authorization supported"

### ISSUE THREAD

**Issue by WilliamDrive** [sirensolutions/sentinl#140]
Hi, 

   I installed the sentinl 5.2.2-1 version since my kibana is 5.2.2 and created new watcher. the new alarms were created without problem. 
   but i could not see the email alert. and I tried to find the configuration for email settings in kibana.yml file.  it seems that there is no email settings. 
   where could I find those email settings?

thanks,
William

**Comment by SergeyBondarenko** [comment]
Hi @WilliamDrive 
You have to put email settings inti kibana.yml, look our [WiKi](https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example), for example:
```
sentinl:
  settings:
    email:
      active: true
      user: anUser@gmail.com
      password: aPassword
      host: smtp.gmail.com
      ssl: false
```
If you use Gmail, you need to [enable unsafe apps](https://support.google.com/accounts/answer/6010255?hl=en).
If you have another mail server, for example, a locally configured postfix, test if it works, Linux way:
```
echo "hello trex" | mail -s "mail for trex" receiver@gmail.com -- -f sender@localhost.it
```
Please attach the watcher config, you can get it from the Raw tab.
