### ISSUE TITLE
Not getting any Emails or Alarms

### ISSUE THREAD

**Issue by bopagama** [sirensolutions/sentinl#163]
I have Kibana Version 5.4 and Sentinl 5.4
I have config Email settings in Kibana.yml adn created a simple watch. But I'm not getting any Email Alerts or any Alarms. Mu watch config is as follows,
```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_5d2n3vy6t",
  "_score": 1,
  "_source": {
    "title": "watcher_title",
    "disable": false,
    "uuid": "new_watcher_5d2n3vy6t",
    "trigger": {
      "schedule": {
        "later": "every 30 secs"
      }
    },
    "input": {
      "simple": {
        "name": "John"
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total >= 0"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h0m30s",
        "email": {
          "to": "**********@gmail.com",
          "from": "*********@***********.com",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Alert",
          "stateless": false
        }
      }
    }
  }
}
```
My Email settings in kibana.yml file as follows ,

```
sentinl:
  es:
    timefield: '@timestamp'
    default_index: watcher
    type: watch
    alarm_index: watcher_alarms
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      user: ***********
      password: **********
      host: ***********
      ssl: true
      timeout: 10000  # mail server connection timeout
report:
      active: true
      tmp_path: /tmp/


```
And I'm getting a bunch of following log messages in kibana logs

```
{"type":"log","@timestamp":"2017-07-17T06:14:30Z","tags":["status","info","Sentinl"],"pid":764,"message":"Executing action: new_watcher_5d2n3vy6t"}
{"type":"log","@timestamp":"2017-07-17T06:15:00Z","tags":["status","info","Sentinl"],"pid":764,"message":"Executing watcherConfig: new_watcher_5d2n3vy6t"}
```

Any Ideas what would be my mistake?

**Comment by lmangani** [comment]
Could be a bunch of things. Most likely, your response is empty tho - I would remove the ```=````as a starter from your condition: ```payload.hits.total >= 0```

**Comment by bopagama** [comment]
I did that but nothing happens.

**Comment by lmangani** [comment]
Set your Kibana to debug mode and watch the logs as this executes. It's impossible for us to imagine what the response might be and/or if your email settings are correct. You can use something like [mailtrap](https://mailtrap.io/) to verify if this is the case.

**Comment by bopagama** [comment]
This is the logs I'm getting,

```
{"type":"log","@timestamp":"2017-07-17T06:49:55Z","tags":["status","debug","Sentinl"],"pid":3159,"message":"Reloading Watchers..."}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","info","Sentinl"],"pid":3159,"message":"Executing watcherConfig: new_watcher_5d2n3vy6t"}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","debug","Sentinl","WATCHER DEBUG"],"pid":3159,"message":"{ _index: 'watcher',\n  _type: 'watch',\n  _id: 'new_watcher_5d2n3vy6t',\n  _score: 1,\n  _source: \n   { title: 'watcher_title',\n     disable: false,\n     uuid: 'new_watcher_5d2n3vy6t',\n     trigger: { schedule: [Object] },\n     input: { simple: [Object] },\n     condition: { script: [Object] },\n     transform: { script: [Object] },\n     actions: { email_admin: [Object] } } }"}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","info","Sentinl"],"pid":3159,"message":"Executing action: new_watcher_5d2n3vy6t"}
{"type":"log","@timestamp":"2017-07-17T06:50:00Z","tags":["status","debug","Sentinl","WATCHER TASK"],"pid":3159,"message":"Watcher new_watcher_5d2n3vy6t search request or condition malformed"}
```
What does it mean by 

> search request or condition malformed?

**Comment by lmangani** [comment]
@bopagama as per above, if we don't know the response it's all guesswork. Sentinl is a client to ES like any other. Can you execute your query in Sense and get any results back?

**Comment by bopagama** [comment]
What is Sense?

**Comment by lmangani** [comment]
Sense (was) a plugin for Kibana, now included in 5.x by default and it's used to manually run and debug queries against Elasticsearch from the UI - I assume you are not familiar with ES queries yet, so I suggest you start with our default examples and a generic query to make the first steps with Sentinl.

**Comment by lmangani** [comment]
Feel free to continue debugging in this ticket, closing as its not a bug but rather a question.

**Comment by bopagama** [comment]
After Changing the Input section I was able to get Alarms. But Still I'm not getting any emails.
Do I need to put bopa@mydomain.com as my username or is it enough just put bopa as my username?

My Raw configuration as follows,

```
{
  "_index": "watcher",
  "_type": "watch",
  "_id": "new_watcher_5d2n3vy6t",
  "_score": 1,
  "_source": {
    "title": "watcher_title",
    "disable": false,
    "uuid": "new_watcher_5d2n3vy6t",
    "trigger": {
      "schedule": {
        "later": "every 30 secs"
      }
    },
    "input": {
      "search": {
        "request": {
          "index": [
            "logstash-*"
          ],
          "body": {}
        }
      }
    },
    "condition": {
      "script": {
        "script": "payload.hits.total > 1"
      }
    },
    "transform": {
      "script": {
        "script": ""
      }
    },
    "actions": {
      "email_admin": {
        "throttle_period": "0h0m30s",
        "email": {
          "to": "*****@*********.com",
          "from": "**************@mydomain.com",
          "subject": "Sentinl Alarm",
          "priority": "high",
          "body": "Alert",
          "stateless": false
        }
      }
    }
  }
}
```
My kibana Email Config as follows,

```
sentinl:
  es:
    timefield: '@timestamp'
    default_index: watcher
    type: watch
    alarm_index: watcher_alarms
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      user: **************@mydomain.com
      password: **********
      host: myemailgateway.com
      ssl: true
      timeout: 10000  # mail server connection timeout
report:
      active: true
      tmp_path: /tmp/
```
