### ISSUE TITLE
Slack Action not working

### ISSUE THREAD

**Issue by bharathphatak** [sirensolutions/sentinl#231]
I have configured slack details in kibana.yml and restart kibana.And configured slack action watchers.

On matching the condition i am getting below error

**"slack"],"pid":1540,"message":"Delivery Disabled!"**

Should i enable any thing else.

This is question and not a issue.

**Comment by lmangani** [comment]
Hi @bharathphatak this should depend on the slack configuration being enabled. 
Could you confirm this is already the case?
```
slack:
      active: true
      username: username
      hook: 'https://hooks.slack.com/services/<token>'
      channel: '#channel'
```
