### ISSUE TITLE
slack action doesn't work

### ISSUE THREAD

**Issue by Morriz** [sirensolutions/sentinl#240]
Using Kibana 5.6.3 with Sentinl 5.6.3 plugin:

1. Issue Description
Slack actions don't work and shows disabled in logs.

2. Reproducing the Issue step-by-step
After enabling and configuring slack with this minimal sentinl section in `kibana.yml`:
```
kibana.yml: |
    sentinl:
      es:
        slack:
          active: true
          username: Sentinl
          hook: 'https://hooks.slack.com/services/xxxxxxxx'

    server.host: '0.0.0.0'
    elasticsearch.url: 'http://elasticsearch:9200'
    logging.dest: stdout
    logging.silent: false
    logging.quiet: false
    logging.verbose: true
```
The hook is tested and works.
But after trigger activation with condition:
```
{
  "script": {
    "script": "true"
  }
}
```
I see in the logs lines with the following:
```
2017 Oct 30 10:55:00 kibana-5c885699f8-gm78s kibana:  {"type":"log","@timestamp":"2017-10-30T10:55:00Z","tags":["status","info","Sentinl"],"pid":13,"message":"Processing action: New slack action 53nml0cbouw"}
2017 Oct 30 10:55:00 kibana-5c885699f8-gm78s kibana:  {"type":"log","@timestamp":"2017-10-30T10:55:00Z","tags":["status","info","Sentinl","scheduler"],"pid":13,"message":"Executing watcher: 1r45igerbjv-i92xy2ajw8n-ruc23plu07j"}
2017 Oct 30 10:55:00 kibana-5c885699f8-gm78s kibana:  {"type":"log","@timestamp":"2017-10-30T10:55:00Z","tags":["status","info","Sentinl","watcher"],"pid":13,"message":"SUCCESS! Watcher has been executed: 1r45igerbjv-i92xy2ajw8n-ruc23plu07j."}
2017 Oct 30 10:55:00 kibana-5c885699f8-gm78s kibana:  {"type":"log","@timestamp":"2017-10-30T10:55:00Z","tags":["status","info","Sentinl","watcher"],"pid":13,"message":"Executing action: 1r45igerbjv-i92xy2ajw8n-ruc23plu07j"}
2017 Oct 30 10:55:00 kibana-5c885699f8-gm78s kibana:  {"type":"log","@timestamp":"2017-10-30T10:55:00Z","tags":["status","info","Sentinl","slack"],"pid":13,"message":"Delivery Disabled!"}
```

3. Expected Results vs. Actual Results

I expect the slack action to proceed.

4. Additional Details

I have not been able to increase verbose debug output, even though I set the logging config according to the kibana instructions. Is there something I can do to increase the plugins' verbosity?

**Comment by lmangani** [comment]
Hi @Morriz 
Your configuration is wrong, the slack config belongs under ```settings``` rather than ```es``` block:
```
kibana.yml: |
    sentinl:
      settings:
        slack:
          active: true
          username: Sentinl
          hook: 'https://hooks.slack.com/services/xxxxxxxx'
```
Please refer to our [wiki](https://github.com/sirensolutions/sentinl/wiki/SENTINL-Config-Example#example-extended) for an example.

**Comment by Morriz** [comment]
Please look carefully, as that is already the case ;)

**Comment by Morriz** [comment]
You are right, I cleaned up too much of the config and screwed up ;)

**Comment by lmangani** [comment]
Awesome - so you confirm it works fine?

**Comment by Morriz** [comment]
Nope, still not working with:

```
  kibana.yml: |
    sentinl:
      settings:
        slack:
          active: true
          username: Sentinl
          hook: 'https://hooks.slack.com/services/xxxxxx'

    server.host: '0.0.0.0'
    elasticsearch.url: 'http://elasticsearch:9200'
    logging.dest: stdout
    logging.silent: false
    logging.quiet: false
    logging.verbose: true
```
