### ISSUE TITLE
sentinl config action email alarm

### ISSUE THREAD

**Issue by mofei-123** [sirensolutions/sentinl#248]
i cconfig sentinl email alarm,but can not receive the alarm mail, please help me, how to troubleshoot the cause of the problem, thank you!

1. Issue Description

2. Reproducing the Issue step-by-step

3. Expected Results vs. Actual Results

4. Additional Details

**Comment by sethyes** [comment]
You need to provide your configuration at the bare minimum. These logs are useless with it.

**Comment by sergibondarenko** [comment]
@mofei-123 
No alert emails? You have to do three following things:
1. Basic config, kibana.yml:
```
logging.verbose: true
sentinl:
  settings:
    email:
      active: true
      host: beast-cave
      ssl: false
    report:
      active: true
      tmp_path: /tmp/
```
2. Check your server using some email client, for example `mailx`:
```
mailx -S smtp=<smtp-server-address> -r <from-address> -s <subject> -v <to-address> < body.txt
```  
3. Create a watcher like in this video https://youtu.be/PiUbmzJ1F5U

Let me know if it works for you.
