### ISSUE TITLE
bug : report did'twork with kibana with searchguard  plugin.

### ISSUE THREAD

**Issue by cyberdak** [sirensolutions/sentinl#265]
i use kibana 5.4.3 with searchguard  plugin.
it has a login page and session manager.

when i config a dashboard like this . 

    "actions": {
      "测试报表": {
        "throttle_period": "0h15m0s",
        "report": {
          "to": "to@qq.com",
          "from": "from@qq.com",
          "subject": "Sentinl Report",
          "priority": "high",
          "body": "Sample Sentinl Screenshot Report",
          "save": true,
          "snapshot": {
            "res": "1280x900",
            "url": "http://10.126.126.75:45601/app/kibana#/visualize/edit/132239f0-b7a0-11e7-bae5-ab26c36b7aaf?embed=true&_g=(refreshInterval%3A(display%3A'1%20minute'%2Cpause%3A!t%2Csection%3A2%2Cvalue%3A60000)%2Ctime%3A(from%3Anow%2Fd%2Cmode%3Aquick%2Cto%3Anow%2Fd))",
            "path": "/tmp/",
            "params": {
              "delay": 5000,
              "crop": false,
              "username": "admin",
              "password": "admin"
            }
          }
        }
      }
    }

i only receive a login page reporter.

![{8070C690-00DC-42BB-A09E-4912675469BF}.jpg](https://i.loli.net/2017/12/11/5a2e51d289dc7.jpg)

so, can sentinl reporter work with searchguard  plugin in kibana?

**Comment by sergibondarenko** [comment]
@cyberdak please show us kibana.yml part related to Sentinl

**Comment by cyberdak** [comment]
```
server.port: 45601

server.host: "0.0.0.0"

elasticsearch.url: "http://10.126.89.88:29200"

elasticsearch.username: "user"
elasticsearch.password: "pwd"

sentinl:
  sentinl:
    history: 20
    results: 50
  settings:
    email:
      active: true
      user: "user"
      password: "pwd"
      host: "smtp.qq.com"
      ssl: true
      timeout: 10000  # mail server connection timeout
    webhook:
      active: true
      method: POST
      host: host
      port: 9200
      path: ':/{{payload.watcher_id}'
      body: '{{payload.watcher_id}}{payload.hits.total}}'
    report:
      active: true
      tmp_path: /tmp/

```
