### ISSUE TITLE
Sentinl  report sending unknown format 

### ISSUE THREAD

**Issue by umeshvasam** [sirensolutions/sentinl#269]
I have given kibana dashboard url while creating report using sentinl. I am receiving report but unknown format like below attached image.Please find below my kibana.yml configuration as well.
```
sentinl:
  settings:
    email:
      active: true
      host: mail.****com
      ssl: false
    report:
      active: true
      tmp_path: /tmp
![cid_my_report](https://user-images.githubusercontent.com/34505716/33932267-777e5aa0-e018-11e7-94a7-347337bea17a.png)

```
