### ISSUE TITLE
Need to define smtp port

### ISSUE THREAD

**Issue by varun0002** [sirensolutions/sentinl#289]
Issue Description: We are using AWS SES and unable to send email using this environment with SSL:true it gives Error: connection encountered an error &  with SSL:false it gives Error: authorization.failed. It appears with AWS SES we need to use port 587. However, smtp.js uses port 25 for non-ssl and port 465 for ssl. Please let us know how to define/configure port # for smtp server.

Expected Results: Need to define parameter/configuration to define smtp port.

using 5.4.1 version

**Comment by varun0002** [comment]
Able to resolve this issue by updating smtp.js, from _this.tls = options.tls || false;__ to _this.tls = options.tls || true;_ However, it'll be better to have tls enable & custom port option in settings/configuration.

**Comment by lmangani** [comment]
@varun0002 thanks! we'll definitely include this on the configurable options in future releases.

**Comment by Arvon2014** [comment]
Now i have the same problem. Is this problem solved?
@lmangani

**Comment by lmangani** [comment]
@Arvon2014 6.x or 5.x ?

**Comment by Arvon2014** [comment]
My version is 6.2.2 
I found that i didn't define the port but it works well, My smtp server port is 587,Has it been dealt with in this version?
And where can i view related documents

**Comment by lmangani** [comment]
@Arvon2014 You said you both 'have the same problem` and `it works well` - which one is it? :)
The currently available docs are at [http://sentinl.readthedocs.io/en/latest/](http://sentinl.readthedocs.io/en/latest/) feel free to contribute with any extension if you see fit.

**Comment by Arvon2014** [comment]
At the beginning I found no place to fill in the port，so i write as 
```
sentinl:
  settings:
    email:
      active: true
      user:  xxx.xxx.cn
      password: xxx
      host: smtp.xxx.org:587
      ssl: true
      timeout: 10000
    report:
      active: true
      tmp_path: /tmp/
```
this time it can‘t work

----
then
I remove the port from the configuration file ，And now it works well
```
sentinl:
  settings:
    email:
      active: true
      user:  xxx.xxx.cn
      password: xxx
      host: smtp.xxx.org
      ssl: true
      timeout: 10000
    report:
      active: true
      tmp_path: /tmp/
```
And you said The document is my reference now.  I didnt' find relate config
So  Is the right way to configure without port?
Thank you for your replay！！
