### ISSUE TITLE
how can i set custom email port?

### ISSUE THREAD

**Issue by huyansheng3** [sirensolutions/sentinl#316]
```
sentinl:
  settings:
    email:
      active: true
      user: smtp_username
      password: smtp_password
      host: smtp.server.com
      ssl: true
    report:
      active: true
      tmp_path: /tmp/
```

```
  // sentinl/server/lib/actions/helpers/email.js
  constructor(args) {
    const { user, password, host, ssl, timeout } = args;
    this.server = emailjs.server.connect({
      user,
      password,
      host,
      ssl,
      timeout
    });
  }
```
email.js contructor only handle some args for  emailjs.server.connect, but dont exist port or any other options. Is better  provider other options for user ?

maybe can write as blew.

```
  // sentinl/server/lib/actions/helpers/email.js
  constructor(args) {
    const { user, password, host, ssl, timeout, ...restOpts } = args;
    this.server = emailjs.server.connect({
      user,
      password,
      host,
      ssl,
      timeout,
      ...restOpts
    });
  }
```
