### ISSUE TITLE
Error executing command to extract phantom ports

### ISSUE THREAD

**Issue by yabir** [sirensolutions/sentinl#327]
**1. Sentinl and Kibana version** 

Kibana: 6.2.1 (Official docker container, OS: CentOS)
Sentinl release: 6.2.1

**2. Issue description**

The watchers and the actions are working correctly, but i'm getting this error using a report action:

from kibana log:
> "fail to report, HeadlessError: Error executing command to extract phantom ports: Error: Command failed: ss -nlp | grep \"[,=]354,\" || netstat -nlp | grep \"[[:space:]]354/\"\n/bin/sh: ss: command not found

I have phantomjs installed , version 2.1.1. For the installation I followed the Sentinl Wiki command:
> npm install phantomjs-prebuilt -g

Here is my sentinl configuration: 

```
sentinl:
  es:
    host: XXX
    port: 9200
    timefield: '@timestamp'
  settings:
    email:
      active: true
      user: XXXXXX
      password: XXXXX
      host: XXXXX
      ssl: true
    report:
      active: true
      tmp_path: /tmp/
      search_guard: false
      simple_authentication: false
    slack:
      active: true
      username: XXXX
      hook: XXXXX
      channel: XXXX
```

Any ideas?
