### ISSUE TITLE
Struggling to send first report

### ISSUE THREAD

**Issue by buinauskas** [sirensolutions/sentinl#348]
1. Sentinl and Kibana version 
6.2.2
2. Issue description
Trying to create my first report that would look at exception log and send 5 endpoints that have happened the day before
3. Reproducing the issue step-by-step
I've got the following query which works just fine in Kibana Dev Tools as expected:
``` json
{
  "size": 0,
  "query": {
    "range": {
      "@timestamp": {
        "gte": "now-1d/d",
        "lt": "now/d"
      }
    }
  },
  "aggs": {
    "URI": {
      "terms": {
        "field": "URI.keyword",
        "size": 5
      }
    }
  }
}
```
I went to Sentinl app in Kibana and created a new Watcher.
Added a random name and left default schedule of every 5 minutes
Created the following input:
``` json
{
  "search": {
    "request": {
      "indices": [
        "error-*"
      ],
      "body": {
        "size": 0,
        "query": {
          "range": {
            "@timestamp": {
              "gte": "now-1d/d",
              "lt": "now/d"
            }
          }
        },
        "aggs": {
          "URI": {
            "terms": {
              "field": "URI.keyword",
              "size": 5
            }
          }
        }
      }
    }
  }
}
```
Left conditions and transformations empty
Added a Slack Action with defaults
Saved the whole thing.
Tried to execute watcher from UI and got the following exception:
```
Error: fail to get watcher 73c555c0-28ee-11e8-b3e5-5be74be89621
    at Watcher.<anonymous> (http://lv-elastic1-uk:5601/bundles/sentinl.bundle.js?v=16588:1:280080)
    at tryCatch (http://lv-elastic1-uk:5601/bundles/vendors.bundle.js?v=16588:121:99780)
    at Generator._invoke (http://lv-elastic1-uk:5601/bundles/vendors.bundle.js?v=16588:121:101855)
    at Generator.prototype.(anonymous function) [as throw] (http://lv-elastic1-uk:5601/bundles/vendors.bundle.js?v=16588:121:100064)
    at step (http://lv-elastic1-uk:5601/bundles/sentinl.bundle.js?v=16588:1:276251)
    at http://lv-elastic1-uk:5601/bundles/sentinl.bundle.js?v=16588:1:276412
```

4. Expected results vs. actual results
I'd expect this to trigger an alert, however I'm getting an exception
5. Sample of data
Query response:
``` json
{
  "took": 221,
  "timed_out": false,
  "_shards": {
    "total": 10,
    "successful": 10,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1803,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "URI": {
      "doc_count_error_upper_bound": 31,
      "sum_other_doc_count": 1428,
      "buckets": [
        {
          "key": "www.company.com/portal/results",
          "doc_count": 91
        },
        {
          "key": "www.company.com/api/search",
          "doc_count": 90
        },
        {
          "key": "www.company.com/portal/analysis/downloadpdf",
          "doc_count": 75
        },
        {
          "key": "www.company.com/portal/account/login",
          "doc_count": 60
        },
        {
          "key": "www.company.com/portal/analysis/tab",
          "doc_count": 58
        }
      ]
    }
  }
}
```
6. Additional details
`/etc/kibana/kibana.yml` has the following config:
``` yaml
sentinl:
  es:
    host: localhost
    port: 9200
    timefield: '@timestamp'
    default_index: watcher
    default_type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
    results: 50
  settings:
    slack:
      active: true
      username: Sentinl
      hook: 'https://hooks.slack.com/services/remaining_part_of_webhook'
      channel: '#channel'
    report:
      active: true
      tmp_path: /tmp/
      search_guard: false
      simple_authentication: false
```
