### ISSUE TITLE
fail to get watcher 

### ISSUE THREAD

**Issue by Efeyabel** [sirensolutions/sentinl#385]
## 1. Sentinl and Kibana version 

Kibana 6.2.2
Sentinl 6.2.2

## 2. Issue description

`fail to get watcher 1e0eb200-3660-11e8-8ee6-2d3b42c859e8`

## 3. Reproducing the issue step-by-step

Try to make a new watcher and run it

## 5. Sample of data

My watcher
```
{
  "actions": {
    "New slack action 6cjr3lh2p4g": {
      "throttle_period": "0h0m5s",
      "slack": {
        "channel": "#appisphera_sentinl",
        "message": "-------------------------------------\n*Anomalias de las ultimas 6 horas en Bitcoins*:\n\n*Anomalias:*\n\n{{#payload.hits.hits}}\n\n{{#_source}}\n- {{timestamp}} : {{last}} E , {{volume}} volumen\n{{/_source}}\n\n{{/payload.hits.hits}}\n--------------------------------------",
        "stateless": false
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [
          "cripto_anomalias"
        ],
        "body": {
          "size": 70,
          "query": {
            "term": {
              "alert": false
            }
          },
          "sort": [
            {
              "timestamp": {
                "order": "desc"
              }
            }
          ]
        }
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total > 0"
    }
  },
  "transform": {
    "script": {
      "script": "var json = payload.hits.hits;var rawData = [];json.forEach(function (item) {rawData.push(item._source);});rawData.forEach(function(value, number, array){value.timestamp = (new Date(value.timestamp*1000).toLocaleString();});payload.hits.hits = json;"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 5 minutes"
    }
  },
  "disable": false,
  "report": false,
  "title": "deteccionAnomalias"
}
```

## 6. Additional details

Check if exsist:
```
GET /.kibana/_search
{
    "size": 60,
    "query": {
        "term":{
            "_id": "sentinl-watcher:1e0eb200-3660-11e8-8ee6-2d3b42c859e8"
        }
    }
}
```

Return 

```
{
    "took": 0,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
            {
                "_index": ".kibana",
                "_type": "doc",
                "_id": "sentinl-watcher:1e0eb200-3660-11e8-8ee6-2d3b42c859e8",
                "_score": 1,
                "_source": {
                    "type": "sentinl-watcher",
                    "updated_at": "2018-04-02T11:12:46.348Z",
                    "sentinl-watcher": {
                        "title": "deteccionAnomalias",
                        "input": {
                            "search": {
                                "request": {
                                    "index": [
                                        "cripto_anomalias"
                                    ],
                                    "body": {
                                        "size": 70,
                                        "query": {
                                            "term": {
                                                "alert": false
                                            }
                                        },
                                        "sort": [
                                            {
                                                "timestamp": {
                                                    "order": "desc"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        },
                        "actions": {
                            "New slack action 6cjr3lh2p4g": {
                                "throttle_period": "0h0m2s",
                                "slack": {
                                    "channel": "#appisphera_sentinl",
                                    "message": "-------------------------------------\n*Anomalias de las ultimas 6 horas en Bitcoins*:\n\n*Anomalias:*\n\n{{#payload.hits.hits}}\n\n{{#_source}}\n- {{timestamp}} : {{last}} E , {{volume}} volumen\n{{/_source}}\n\n{{/payload.hits.hits}}\n--------------------------------------",
                                    "stateless": false
                                }
                            }
                        },
                        "transform": {
                            "script": {
                                "script": "var json = payload.hits.hits;var rawData = [];json.forEach(function (item) {rawData.push(item._source);});rawData.forEach(function(value, number, array){value.timestamp = (new Date(value.timestamp*1000).toLocaleString();});payload.hits.hits = json;"
                            }
                        },
                        "condition": {
                            "script": {
                                "script": "payload.hits.total > 0"
                            }
                        },
                        "report": false,
                        "disable": true,
                        "trigger": {
                            "schedule": {
                                "later": "every 5 minutes"
                            }
                        }
                    }
                }
            }
        ]
    }
}
```

**Comment by sergibondarenko** [comment]
@Efeyabel please provide output from the Kibana console.

The output should be with the verbose option enabled:
**kibana/config/kibana.yml**
```
logging.verbose: true
```

**Comment by Efeyabel** [comment]
``3/4/2018 10:30:35  log   [08:30:35.384] [debug][plugin] Checking Elasticsearch version
3/4/2018 10:30:35respons [08:30:35.691]  POST /api/saved_objects/bulk_get 200 26ms - 9.0B
3/4/2018 10:30:36  log   [08:30:36.045] [debug][Sentinl][get_elasticsearch_client] impersonating Elasticsearch client by elastic:changeme
3/4/2018 10:30:36  log   [08:30:36.047] [debug][Sentinl][watcher] executing watcher: 1e0eb200-3660-11e8-8ee6-2d3b42c859e8
3/4/2018 10:30:36  log   [08:30:36.067] [debug][license][xpack] Calling [data] Elasticsearch _xpack API. Polling frequency: 30001
3/4/2018 10:30:36respons [08:30:36.044]  POST /api/sentinl/watcher/_execute 406 34ms - 9.0B
3/4/2018 10:30:36  log   [08:30:36.193] [debug][esqueue][reporting][worker] jfjekb2500011d5d4358s75h - querying for outstanding jobs

**Comment by sergibondarenko** [comment]
@Efeyabel ok, now please show me kibana.yml

**Comment by Efeyabel** [comment]
```
##CONFIGURACION PARA KIBANA##
server.name: kibana
server.host: "0"
elasticsearch.url: http://10.42.83.207:9200
elasticsearch.username: elastic
elasticsearch.password: changeme
xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.security.enabled: false
logging.verbose: true
sentinl:
  es:
    host: 10.42.83.207
    port: 9200
    timefield: '@timestamp'
    default_index: watcher
    default_type: sentinl-watcher
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
    results: 50
  settings:
    authentication:
      enabled: true
      username: 'elastic'
      password: 'changeme'
      cert:
        selfsigned: true
    email:
      active: true
      user: xxxxx
      password: xxxxx
      host: xxxx
      ssl: true
      timeout: 10000 # mail server connection timeout
    report:
      active: true
      tmp_path: /usr/share/kibana/reportes
      search_guard: false
      simple_authentication: false
    slack:
      active: true
      username: user@heritas.es
      hook: 'https://hooks.slack.com/services/[...]'
      channel: '#appisphera_sentinl

```

**Comment by sergibondarenko** [comment]
@Efeyabel so, you have x-pack authentication working, right?

Then you `authentication` part of the config misses `mode`:
```
...
    settings:
      authentication:
        enabled: true
        mode:
          xpack: true
```

**Comment by sergibondarenko** [comment]
Here is the doc http://sentinl.readthedocs.io/en/latest/Authentication/

**Comment by Efeyabel** [comment]
Nope, i dont use any authentication sistem.

**Comment by lmangani** [comment]
@sergibondarenko shall we add this to the FAQ for this specific error checklist?

**Comment by sergibondarenko** [comment]
@lmangani yes, we can.

**Comment by Efeyabel** [comment]
I switch to false and still not work

**Comment by sergibondarenko** [comment]
@Efeyabel 
Do you have the same error? 
Are you sure the Kibana was restarted?

**Comment by sergibondarenko** [comment]
@Efeyabel what result does the following command produce?
```
curl -XGET <es_protocol>//:<es_ip_addr_or_hostname>:<es_port>/.kibana/_search/?pretty
```

**Comment by sergibondarenko** [comment]
Let's apply a minimal configuration, then add options if they are required:
```
sentinl:
  settings:
    email:
      active: true
      host: localhost 
    report:
      active: true
      executable_path: '/usr/bin/chromium' # path to Chrome v59+ or Chromium v59+
```

**Comment by Efeyabel** [comment]
All other thigs works pretty well, i can edit, delete and create Watchers, but when y try to run it i got the error

**Comment by sergibondarenko** [comment]
@Efeyabel let's reinstall Sentinl from the latest release
```
# Stop Kibana first
cd kibana
rm -rf plugins/sentinl
./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.3-1/sentinl-v6.2.2.zip
# Start Kibana when finished
```
Use the minimal Sentinl config:
```
sentinl:
  settings:
    email:
      active: true
      host: localhost 
    report:
      active: true
      executable_path: '/usr/bin/chromium' # path to Chrome v59+ or Chromium v59+
```
