### ISSUE TITLE
Config failing on default options

### ISSUE THREAD

**Issue by callahan22** [sirensolutions/sentinl#388]
Sentinl version & Kibana version: 6.0.0 running on Windows 2012

**Issue description**
Kibana fails to run with the default config set up in Sentinl. I realise the executable_path is incorrect for a Windows box but as I can't get it to accept the executable_path variable, it didn't seem important at the moment!

I have the following config defined in Kibana.yml :

```
logging.dest: stdout
logging.silent: false
logging.quiet: false
logging.verbose: true

sentinl:
  es:
    host: 'localhost'
    port: 9200
    protocol: 'http'
    # results: 50
    timefield: '@timestamp'
    default_type: 'doc'
    alarm_index: 'watcher_alarms'
    alarm_type: 'sentinl-alarm'
  settings:
    email:
      active: true
      host: 'smtp.mail.com'
      # user: 'admin'
      # password: 'password'
      # port: 25
      # domain: 'my.domain'
      # ssl: false
      # tls: false
      # authentication: ['PLAIN', 'LOGIN', 'CRAM-MD5', 'XOAUTH2']
      # timeout: 10000  # mail server connection timeout
      # cert:
      #   key: '/full/sys/path/to/key/file'
      #   cert: '/full/sys/path/to/cert/file'
      #   ca: '/full/sys/path/to/ca/file'
    report:
      active: true
      executable_path: '/usr/bin/chromium-browser'
      file:
         pdf:
           format: 'A4'
           landscape: true
         screenshot:
           width: 1280
           height: 900
```

Starting Kibana, causes these errors to be logged and the Kibana web interface to become inaccessible. Bolded for ease of reading...
```
{"type":"log","@timestamp":"2018-04-03T17:02:22Z","tags":["fatal"],"pid":179888,"level":"fatal","message":"child \"sentinl\" fails because [child \"es\" fails because **[\"protocol\" is not allowed**, **\"default_type\" is not allowed]**, child \"settings\" fails because [child \"report\" fails because **[\"executable_path\" is not allowed**, **\"file\" is not allowed]]]"**,"error":{"message":"child \"sentinl\" fails because [child \"es\" fails because **[\"protocol\" is not allowed**, **\"default_type\" is not allowed]**, child \"settings\" fails because [child \"report\" fails because **[\"executable_path\" is not allowed**, **\"file\" is not allowed]]]"**,"name":"ValidationError","stack":"ValidationError: child \"sentinl\" fails because [child \"es\" fails because **[\"protocol\" is not allowed**, **\"default_type\" is not allowed]**, child \"settings\" fails because [child \"report\" fails because **[\"executable_path\" is not allowed,** \"file\" is not allowed]]]\n    at Object.exports.process (C:\\ELK\\kibana\\node_modules\\joi\\lib\\errors.js:181:19)\n    at _validateWithOptions (C:\\ELK\\kibana\\node_modules\\joi\\lib\\any.js:651:31)\n    at root.validate (C:\\ELK\\kibana\\node_modules\\joi\\lib\\index.js:121:23)\n    at Config._commit (C:\\ELK\\kibana\\src\\server\\config\\config.js:118:35)\n    at Config.set (C:\\ELK\\kibana\\src\\server\\config\\config.js:88:10)\n    at Config.extendSchema (C:\\ELK\\kibana\\src\\server\\config\\config.js:61:10)\n    at C:\\ELK\\kibana\\src\\server\\plugins\\plugin_collection.js:23:12\n    at next (native)\n    at step (C:\\ELK\\kibana\\src\\server\\plugins\\plugin_collection.js:53:191)\n    at C:\\ELK\\kibana\\src\\server\\plugins\\plugin_collection.js:53:361"}}
```
Commenting out the the problem options, prevents the issues and allows Kibana to start but obviously prevents me from really using Sentinl.

I'm unsure what I need to change to make this work as expected. If I've missed any required info, please let me know.

**Comment by ebuildy** [comment]
Check configuration here https://github.com/sirensolutions/sentinl/blob/tag-6.2.2/index.js

**Comment by sergibondarenko** [comment]
@callahan22  The correct install procedure is
```
cd kibana
./bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.2/sentinl-v6.2.2.zip
```
Did you do this?

**Comment by sergibondarenko** [comment]
Btw, the following options are applied by default and you can omit them you don't want to change the default values
```
      file:
         pdf:
           format: 'A4'
           landscape: true
         screenshot:
           width: 1280
           height: 900
```
