### ISSUE TITLE
No alerts after update

### ISSUE THREAD

**Issue by avinchakov** [sirensolutions/sentinl#398]
1. Sentinl and Kibana version 
**Kibana 6.2.3
Sentinl 6.2.3**
2. Issue description
After update to 6.2.3 I manualy moved all my alerts(export/inmport json) to the new sentinl (becouse it uses .kibana-6 index at now).  But now the schedule does not work, manual start-up works.
Debug kibana logs:
```
  | Apr 16 2018, 15:34:55 | cluster disabled

  | Apr 16 2018, 15:34:25 | auth enabled: false

  | Apr 16 2018, 15:34:25 | cluster disabled

  | Apr 16 2018, 15:34:25 | auth via Kibana server elasticseaarch plugin

  | Apr 16 2018, 15:34:25 | reloading watchers...

  | Apr 16 2018, 15:34:25 | no watchers found

  | Apr 16 2018, 15:33:55 | reloading watchers...

  | Apr 16 2018, 15:33:55 | no watchers found

  | Apr 16 2018, 15:33:55 | cluster disabled

  | Apr 16 2018, 15:33:55 | auth enabled: false

  | Apr 16 2018, 15:33:55 | auth via Kibana server elasticseaarch plugin

  | Apr 16 2018, 15:33:25 | cluster disabled

  | Apr 16 2018, 15:33:25 | auth enabled: false

  | Apr 16 2018, 15:33:25 | no watchers found

  | Apr 16 2018, 15:33:25 | auth via Kibana server elasticseaarch plugin

  | Apr 16 2018, 15:33:25 | reloading watchers...

  | Apr 16 2018, 15:32:55 | auth via Kibana server elasticseaarch plugin

  | Apr 16 2018, 15:32:55 | reloading watchers...

  | Apr 16 2018, 15:32:55 | no watchers found

  | Apr 16 2018, 15:32:55 | cluster disabled

  | Apr 16 2018, 15:32:55 | auth enabled: false

  | Apr 16 2018, 15:32:25 | reloading watchers...

  | Apr 16 2018, 15:32:25 | cluster disabled

  | Apr 16 2018, 15:32:25 | auth enabled: false

  | Apr 16 2018, 15:32:25 | auth via Kibana server elasticseaarch plugin

  | Apr 16 2018, 15:32:25 | no watchers found

  | Apr 16 2018, 15:31:55 | auth via Kibana server elasticseaarch plugin

  | Apr 16 2018, 15:31:55 | no watchers found

  | Apr 16 2018, 15:31:55 | cluster disabled

  | Apr 16 2018, 15:31:55 | reloading watchers...

  | Apr 16 2018, 15:31:55 | auth enabled: false

  | Apr 16 2018, 15:31:25 | no watchers found

```

3. Reproducing the issue step-by-step
Upgrade sentinl from v5 to v6 with simple ELK instance and move old alerts to the new index.
4. Expected results vs. actual results
Expected that all willl working.
5. Sample of data
```
curl -XGET http://localhost:9200/.kibana/doc/sentinl-watcher:f4150250-3e30-11e8-922a-310a40d2e233?pretty
{
  "_index" : ".kibana-6",
  "_type" : "doc",
  "_id" : "sentinl-watcher:f4150250-3e30-11e8-922a-310a40d2e233",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "type" : "sentinl-watcher",
    "updated_at" : "2018-04-12T09:07:40.917Z",
    "sentinl-watcher" : {
      "title" : "Internal Blocks per 30 min",
      "input" : {
        "search" : {
          "request" : {
            "index" : [
              "<net-{now/M{YYYY.MM}}>"
            ],
            "body" : {
              "size" : 100,
              "query" : {
                "bool" : {
                  "must" : [
                    {
                      "query_string" : {
                        "query" : "src_ip:172.16.* AND dst_ip:172.16.*",
                        "analyze_wildcard" : true
                      }
                    },
                    {
                      "range" : {
                        "@timestamp" : {
                          "from" : "now-30m"
                        }
                      }
                    }
                  ]
                }
              },
              "_source" : {
                "excludes" : [ ]
              },
              "aggs" : { }
            }
          }
        }
      },
      "actions" : {
        "sysadmins@xsolla.com" : {
          "throttle_period" : "0h0m1s",
          "email_html" : {
            "to" : "admins@mail.com",
            "from" : "elk@mail.com",
            "subject" : "Many Internal Blocks (30min)",
            "body" : "<h1 style=\"color: #5e9ca0;\">Net&nbsp;Event</h1>\n<h2 style=\"color: #2e6c80;\">Total Hits: {{payload.hits.total}}</h2>\n<p>There many internal block. Please check!</p>\n<p>{{#payload.hits.hits}}</p>\n<p><strong>{{_source.message}}</p>\n<p>{{/payload.hits.hits}}</p>",
            "html" : "<h1 style=\"color: #5e9ca0;\">Net&nbsp;Event</h1>\n<h2 style=\"color: #2e6c80;\">Total Hits: {{payload.hits.total}}</h2>\n<p>There many internal block. Please check!</p>\n<p>{{#payload.hits.hits}}</p>\n<p><strong>{{_source.message}}</p>\n<p>{{/payload.hits.hits}}</p>"
          }
        }
      },
      "transform" : { },
      "condition" : {
        "script" : {
          "script" : "payload.hits.total > 30"
        }
      },
      "report" : false,
      "disable" : false,
      "trigger" : {
        "schedule" : {
          "later" : "every 30 mins"
        }
      }
    }
  }
}
```

**Comment by sergibondarenko** [comment]
@avinchakov 
Do you use Sentinl from [the latest pre-release](https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-2)? Please do it.
Also, post content of `kiban/config/kibana.yml` file.

**Comment by avinchakov** [comment]
@sergibondarenko 
Yes, I use the latest.
```
server.host: "localhost"
elasticsearch.pingTimeout: 3000
elasticsearch.requestTimeout: 60000
logging.dest: stdout
logging.silent: false
logging.quiet: false
logging.verbose: true
ops.interval: 60000
console.enabled: false
sentinl:
  es:
    host: localhost
    port: 9200
    timefield: '@timestamp'
    default_type: watch
    alarm_index: watcher_alarms
    alarm_type: sentinl-alarm
    script_type: sentinl-script
    results: 600
  settings:
    email:
      active: true
      host: smtp.srv.local
      timeout: 10000  # mail server connection timeout
      ssl: false
    slack:
      active: true
      hook: 'https://hooks.slack.com/services/T02A1.....WlXlrt'
      channel: '#test-team'
    report:
      active: true
```
