### ISSUE TITLE
v6.2.3 not starting

### ISSUE THREAD

**Issue by mreilly82** [sirensolutions/sentinl#400]
1. Sentinl and Kibana version 
Kibana v6.2.3 Sentinl v6.2.3
Ubuntu 16.04

2. Issue description
Sentinl will not start up when starting up Kibana. See the floowing message in logs:
{"type":"log","@timestamp":"2018-04-16T20:40:49Z","tags":["plugin","warning"],"pid":16820,"path":"/usr/share/kibana/plugins/sentinl","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/sentinl"}
Also, when checking Kibana service status it says active but the host:5601 will not load

3. Reproducing the issue step-by-step
Installed Sentinl following the documentation. Added simple config for Sentinl 6.x as per documentation.
Start Kibana service, checked logs 

4. Expected results vs. actual results
It is epxected that Sentinl is up and running but it is not.

5. Sample of data
{"type":"log","@timestamp":"2018-04-16T20:40:49Z","tags":["plugin","warning"],"pid":16820,"path":"/usr/share/kibana/plugins/sentinl","message":"Skipping non-plugin directory at /usr/share/kibana/plugins/sentinl"}

6. Additional details
I had uninstalled Kibana and started fresh install of both Kibana/Sentinl and problem still exists.

**Comment by sergibondarenko** [comment]
@mreilly82 
Is it an upgrade from old Sentinl? Post `kibana.yml` config here.

**Comment by sergibondarenko** [comment]
Do you use the latest pre-release? https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.3-2
Please do.

**Comment by sergibondarenko** [comment]
@mreilly82 Do you use authentication?

**Tip:** at first try with minimal config:
```
sentinl:
  settings:
    email:
      active: true
      host: beast
    report:
      active: true
      executable_path: '/usr/bin/chromium' # path to Chrome v59+ or Chromium v59+
```
