### ISSUE TITLE
Windows Report Issue

### ISSUE THREAD

**Issue by AlphaJosh** [sirensolutions/sentinl#402]
I am using Kibana v6.2.3 with the Sentinl 6.2.3 plugin and I am struggling to understand how to create a report of a visualization. Could someone help me please?

I am not seeing any errors and can see scheduler working in the logs so I don't  believe there is problem.

I would like some timelion graphs to be emailed out on the first day of the month.

Do I need to install Spy, Kibi or Kaae in addition to Kibana?

How/where do I reference the visualization/saved object? Does someone have a guide for this please?

Thank you for helping me.

**Comment by sergibondarenko** [comment]
Hey @AlphaJosh 
You can there is a guide in wiki http://sentinl.readthedocs.io/en/latest/Watcher-Wizard/#using-the-wizard 

There are three thing to do:
1. Install Sentinl, look [readme](https://github.com/sirensolutions/sentinl) for help 
2. Configure Sentinl. Here is the minimal config you need in `kibana.yml` to make report work:
```
sentinl:
  settings:
    email:
      active: true
      host: localhost
    report:
      active: true
      executable_path: '/usr/bin/chromium' # path to Chrome v59+ or Chromium v59+
```
  From this doc http://sentinl.readthedocs.io/en/latest/HOWTO-Create-Reports/

3. Create reporter. In Kibana UI go to Sentinl, click `New` in the right top corner, select `Reporter`. Insert correct params for the report action inside the `Actions` tab.
