### ISSUE TITLE
fail to delete alarm/report

### ISSUE THREAD

**Issue by OleksandrSlobodian** [sirensolutions/sentinl#416]
1. Sentinl 6.2.2 / Kibana 6.2.2 

2. fail to delete alarm/report from UI

```{"type":"error","@timestamp":"2018-05-04T17:32:09Z","tags":["warning","process"],"pid":20064,"level":"error","error":{"message":"Unhandled promise rejection (rejection id: 24): TypeError: _boom2.default.serverTimeout is not a function","name":"UnhandledPromiseRejectionWarning","stack":"TypeError: _boom2.default.serverTimeout is not a function\n    at handleESError (/usr/share/kibana/plugins/sentinl/server/lib/handle_es_error.js:33:17)\n    at /usr/share/kibana/plugins/sentinl/server/routes/routes.js:147:22\n    at throw (native)\n    at step (/usr/share/kibana/plugins/sentinl/server/routes/routes.js:54:191)\n    at /usr/share/kibana/plugins/sentinl/server/routes/routes.js:54:402\n    at process._tickDomainCallback (internal/process/next_tick.js:135:7)"},"message":"Unhandled promise rejection (rejection id: 24): TypeError: _boom2.default.serverTimeout is not a function"}```

![screen shot 2018-05-04 at 12 26 46 pm](https://user-images.githubusercontent.com/12740635/39642286-e53f5f92-4f96-11e8-8bc4-221239b7efb2.png)

**Comment by sergibondarenko** [comment]
Do you have authentication configured on Elasticsearch side?
Please show Kibana config.

**Comment by sergibondarenko** [comment]
Did you configure SearchGuard to permit Sentinl server to do operations over `watcher_alarms` index?
For example in `sg_roles.yml`
```
sg_kibana_server:
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
      - cluster:admin/xpack/monitoring*
  indices:
    '?kibana':
      '*':
        - INDICES_ALL
    'watcher*':
      '*':
       - indices:data/read/search
       - MANAGE
       - CREATE_INDEX
       - INDEX
       - READ
       - WRITE
       - DELETE
```
