### ISSUE TITLE
report action: execute report: Phantom immediately exited with: 127 // Ver 6.2.4 stable

### ISSUE THREAD

**Issue by omarix** [sirensolutions/sentinl#495]
Hi all, 

Please I need your help to solve an issue I faced when generating the report using Phantomjs, the alert has been matched and when the report engine start processing its end with the error "**report action: execute report: Phantom immediately exited with: 127**" , knowing that all dependencies are installed 
```
 apt-get install libfontconfig libfreetype6
```

```
{"type":"log","@timestamp":"2018-07-09T23:54:00Z","tags":["debug","Sentinl","report"],"pid":4664,"message":"phantomjs path: /usr/share/kibana/plugins/sentinl/node_modules/phantomjs-prebuilt/bin/phantomjs"}
{"type":"log","@timestamp":"2018-07-09T23:54:00Z","tags":["debug","Sentinl","report"],"pid":4664,"message":"kibi access control: false"}
{"type":"log","@timestamp":"2018-07-09T23:54:00Z","tags":["info","Sentinl","watcher sentinl-watcher:6dd65320-83b2-11e8-a105-e5e01fee097d"],"pid":4664,"message":"successfuly executed"}
{"type":"log","@timestamp":"2018-07-09T23:54:00Z","tags":["error","Sentinl","do_action"],"pid":4664,"message":"report action: execute report: Phantom immediately exited with: 127"}
{"type":"log","@timestamp":"2018-07-09T23:54:10Z","tags":["error","Sentinl","do_action"],"pid":4664,"message":"fail to send email, watcher: sentinl-watcher:6dd65320-83b2-11e8-a105-e5e01fee097d, Error: connection encountered an error"}
```

```
sentinl:
  es:
    host: 'localhost'
    port: 9200
  settings:
    email:
      active: true
      user: xxxxx@xxxxxx.com
      password: 'xxxxxx'
      host: mx.aaaaaaa.net
      port: 465
      ssl: true
      tls: true
    report:
      active: true
      engine: horseman
```

Additional info:
Sentinl and Kibana version : 6.2.4 stable release 

OS; ubuntu 16.04 64bit 

Best regards.
