### ISSUE TITLE
Impersonate is not allowed

### ISSUE THREAD

**Issue by havlan** [sirensolutions/sentinl#508]
1. Sentinl and Kibana version 
Kibana: 6.2.4
Sentinl: 6.2.4 (Wizard)

2. Issue description
Error when installing sentinl from github or from master.

It triggers when passing impersonate: true in kibana.yml file. index.js still has impersonate field included.

3. Reproducing the issue step-by-step
```json
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4-pre-0/sentinl-v6.2.4.zip
Transferring 135709955 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "child "sentinl" fails because [child "settings" fails because [child "authentication" fails because ["imersonate" is not allowed]]]"
```

4. Expected results vs. actual results
Expected installation complete without errors.

5. Sample of data

kibana.yml
```yaml
...
sentinl:
  es:
    host: 'localhost'
    port: 9200
    protocol: 'http'
    results: 50
    timefield: '@timestamp'
    default_type: 'doc'
    alarm_index: 'watcher_alarms'
    alarm_type: 'sentinl-alarm'
  settings:
    authentication:
      enabled: true
      username: 'sentinl'
      password: 'sentinl'
      imersonate: true
...
```

[Kibana logs](https://gist.github.com/havlan/2b027f433db910e7fd1a100bcf6f40df)

6. Additional details
#502 should have fixed this. Maybe it did.
Updated documentation is required. But it's hard to contribute not knowing what broke.
