### ISSUE TITLE
executable_path:

### ISSUE THREAD

**Issue by ankit22550** [sirensolutions/sentinl#527]
1. Sentinl and Kibana version   6.2.3

2. Issue description  executable path

3. Reproducing the issue step-by-step  generating report

4. Expected results vs. actual results

5. Sample of data

6. Additional details

Hello Team,

need help to pass executable_path: '/usr/bin/chromium' # path to Chrome v59+ or Chromium v59+  currently we need to use chromium to generate the report is there any method so we don't need any browsers like we use  an earlier version of sentinl to generate a report

**Comment by sergibondarenko** [comment]
@ankit22550 always check docs if some of your config options don't work in the newest version.

Sentinl has 2 engines for the report fn: `puppeteer` and `horseman` (default). Puppeteer uses Chrome browser, horseman uses PhantomJS.

Sentinl finds a path to a browser automatically except on Windows (will be fixed). But you can set the path to the browser manually:
```
sentinl:
  settings
    report:
      engine: horseman
      horseman:
        browser_path: /full/sys/path
```
OR
```
sentinl:
  settings
    report:
      engine: puppeteer
      puppeteer:
        browser_path: /full/sys/path
```

Related docs
---
https://github.com/sirensolutions/sentinl/blob/master/docs/Config-Example.md#example-extended-1
https://github.com/sirensolutions/sentinl/blob/master/docs/HOWTO-Create-Reports.md
https://github.com/sirensolutions/sentinl/blob/master/docs/Authentication.md#authenticate-report-action

Also, **it is extremely helpful to look at index.js** to see all available options https://github.com/sirensolutions/sentinl/blob/master/index.js#L295

**Comment by ankit22550** [comment]
Hello,


If I don’t want to use browsers  I need to use the phantomjs path to generate a report.


Regards
[http://www.orange.com/sirius/logos_mail/orange_logo.gif]<http://www.orange.com/>
Ankit Kumar
International Orange Labs India
IMT/OLS/GO/IOL/INDIA
CVS 7 357 4124
mob. IN +91 9999853090
Ankit2.kumar@orange.com<mailto:Ankit2.kumar@orange.com>

**Comment by sergibondarenko** [comment]
@ankit22550 
> If I don’t want to use browsers  I need to use the phantomjs path to generate a report.

PhantomJS is a browser too. If you want to use it, just delete `report` section from the kibana.yml. For example, the following config is enough to generate reports (if email server `hostname:25` works):
```
sentinl:
  settings:
    email:
      active: true
      host: hostname
      port: 25
```

The exampe above works only in this release https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.4
