### ISSUE TITLE
Error on installing sentinl

### ISSUE THREAD

**Issue by Ihsan8** [sirensolutions/sentinl#581]
Hi 
I am trying to integrate Sentinl with ELK Stack. I am using kibana version 6.4.1 .I followed https://sentinl.readthedocs.io/en/latest/Installation/ for installation. After installation I configured kibana.yml by adding following lines. 
```
sentinl:
  es:
    host: 'localhost'
    port: 9200
  settings:
    email:
      active: true
      host: "smtp.gmail.com"
      user: "[mygmailaddress@gmail.com]"
      password: "[**********]"
      port: 465
      domain: "gmail.com"
      ssl: true
      tls: false
      authentication: ['PLAIN', 'LOGIN', 'CRAM-MD5', 'XOAUTH2']
```
After installation, I run kibana and got the following  errors.
```
 "FATAL "sentinl.es.host", "sentinl.es.port", "sentinl.settings.email.active", "sentinl.settings.email.host", "sentinl.settings.email.user", "sentinl.settings.email.password", "sentinl.settings.email.port", "sentinl.settings.email.domain", "sentinl.settings.email.ssl", "sentinl.settings.email.tls", "sentinl.settings.email.authentication", and "sentinl.settings.email.timeout" settings were not applied. Check for spelling errors and ensure that expected plugins are installed."
```
So please help me to solve it
