### ISSUE TITLE
Using 6.4.2 Sentinl results in 'Watchers: list watchers : list watcher : Authentication Exception'

### ISSUE THREAD

**Issue by camAtGitHub** [sirensolutions/sentinl#600]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |  6.4.2  |
| Elasticsearc | 6.4.2   |
| Server OS    | Docker on Redhat 7.5
| Browser      |  Firefox       |

#### Original Install Method

- [ ] Release pkg link
- [ ] Gulp
- [ ] Source
- Other: kibana  plugin install https://github.com/sirensolutions/sentinl/releases/download/tag-6.4.2-0/sentinl-v6.4.2.zip

#### Steps to Reproduce
1. Access the Sentinl app fails with the following errors:
```Watchers: list watchers : list watcher : Authentication Exception```
More Info shows:
```Error: list watchers : list watcher : Authentication Exception
SentinlError@https://wa-knsg-elkdev1.acme.local:5601/bundles/sentinl.bundle.js:50:241102
_callee4$@https://wa-knsg-elkdev1.acme.local:5601/bundles/sentinl.bundle.js:50:262600
tryCatch@https://wa-knsg-elkdev1.acme.local:5601/bundles/vendors.bundle.js:43:57426
invoke@https://wa-knsg-elkdev1.acme.local:5601/bundles/vendors.bundle.js:43:61311
defineIteratorMethods/</prototype[method]@https://wa-knsg-elkdev1.acme.local:5601/bundles/vendors.bundle.js:43:58547
step@https://wa-knsg-elkdev1.acme.local:5601/bundles/sentinl.bundle.js:50:259118
step/<@https://wa-knsg-elkdev1.acme.local:5601/bundles/sentinl.bundle.js:50:259286
run@https://wa-knsg-elkdev1.acme.local:5601/bundles/vendors.bundle.js:43:25850
notify/<@https://wa-knsg-elkdev1.acme.local:5601/bundles/vendors.bundle.js:43:26090
flush@https://wa-knsg-elkdev1.acme.local:5601/bundles/vendors.bundle.js:173:132168
```
#### Expected Behavior
No errors

#### Kibana logs and/or server output (attached if relevant)
```
kibana-wazuh-kibana-5 | 2018-10-31T03:46:55.042466000Z {"type":"log","@timestamp":"2018-10-31T03:46:55Z","tags":["error","Sentinl","scheduler"],"pid":1,"message":"fail to schedule watchers: list watchers : find : Request Timeout after 30000ms"}  
kibana-wazuh-kibana-5 | 2018-10-31T03:47:07.888242000Z {"type":"error","@timestamp":"2018-10-31T03:47:07Z","tags":["warning","stats-collection"],"pid":1,"level":"error","error":{"message":"Request Timeout after 30000ms","name":"Error","stack":"Error: Request Timeout after 30000ms\n    at /usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:354:15\n    at Timeout.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:383:7)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"},"message":"Request Timeout after 30000ms"}  
kibana-wazuh-kibana-5 | 2018-10-31T03:47:07.891640000Z {"type":"log","@timestamp":"2018-10-31T03:47:07Z","tags":["warning","stats-collection"],"pid":1,"message":"Unable to fetch data from kibana collector"}```

No other errors logged in ElasticSearch

#### Any additional information
This is a major point - I am running SearchGuard 23.2. I have also applied the SearchGuard requirements as documented here: https://docs.search-guard.com/latest/search-guard-sentinl
 I'm not sure if this a security exception within SearchGuard as SearchGuard logs permission issues encountered and no such errors have been logged.

**Comment by lbesuchet** [comment]
I'm experiencing simillar issue, using ReadonlyREST: _Watchers: list watchers : list watcher : An internal server error occurred_
####  Kibana logs and/or server output
```
kibana    | {"type":"log","@timestamp":"2018-10-31T00:00:00Z","tags":["error","readonlyrest_kbn"],"pid":1,"message":"got an error [500] Internal Server Error for path /api/sentinl/list/watchers"}
kibana    | {"type":"error","@timestamp":"2018-10-31T08:04:36Z","tags":["error","readonlyrest_kbn"],"pid":1,"level":"error","error":{"message":"Cannot read property 'auth' of undefined","name":"Error","stack":"Error: Cannot read property 'auth' of undefined\n    at handleESError (/usr/share/kibana/plugins/sentinl/server/lib/handle_es_error.js:29:17)\n    at handler (/usr/share/kibana/plugins/sentinl/server/routes/watcher.js:38:22)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"},"message":"Cannot read property 'auth' of undefined"}
kibana    | {"type":"error","@timestamp":"2018-10-31T08:04:36Z","tags":[],"pid":1,"level":"error","error":{"message":"Cannot read property 'auth' of undefined","name":"Error","stack":"Error: Cannot read property 'auth' of undefined\n    at handleESError (/usr/share/kibana/plugins/sentinl/server/lib/handle_es_error.js:29:17)\n    at handler (/usr/share/kibana/plugins/sentinl/server/routes/watcher.js:38:22)\n    at <anonymous>\n    at runMicrotasksCallback (internal/process/next_tick.js:121:5)\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/api/sentinl/list/watchers","path":"/api/sentinl/list/watchers","href":"/api/sentinl/list/watchers"},"message":"Cannot read property 'auth' of undefined"}
kibana    | {"type":"response","@timestamp":"2018-10-31T08:04:36Z","tags":[],"pid":1,"method":"post","statusCode":500,"req":{"url":"/api/sentinl/list/watchers","method":"post","headers":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","accept":"application/json, text/plain, */*","origin":"http://localhost:5601","kbn-version":"6.4.2","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","referer":"http://localhost:5601/app/sentinl","accept-encoding":"gzip, deflate, br","accept-language":"fr-CH,fr;q=0.9,en;q=0.8,fr-FR;q=0.7,en-US;q=0.6,de;q=0.5"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://localhost:5601/app/sentinl"},"res":{"statusCode":500,"responseTime":70,"contentLength":9},"message":"POST /api/sentinl/list/watchers 500 70ms - 9.0B"}
kibana    | Debug: internal, implementation, error 
kibana    |     Error: Cannot read property 'auth' of undefined
kibana    |     at handleESError (/usr/share/kibana/plugins/sentinl/server/lib/handle_es_error.js:29:17)
kibana    |     at handler (/usr/share/kibana/plugins/sentinl/server/routes/watcher.js:38:22)
kibana    |     at <anonymous>
kibana    |     at runMicrotasksCallback (internal/process/next_tick.js:121:5)
kibana    |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
kibana    |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by sergibondarenko** [comment]
we have a new release with some fixes, please install it first https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.4-3-public

**Comment by lbesuchet** [comment]
>           we have a new release with some fixes, please install it first https://github.com/sirensolutions/sentinl/releases/tag/tag-6.2.4-3-public

the issue is with kibana/es 6.4.2. Shouldn't we use sentinl tag-6.4.2-0 ?

**Comment by camAtGitHub** [comment]
As mentioned above this bug report is for version 6.4.2 of Kibana, the new release versions of Sentinl only list up to 6.2.4 .
Thanks

**Comment by sergibondarenko** [comment]
@lbesuchet @camAtGitHub  the link for 6.4.2 release is https://github.com/sirensolutions/sentinl/releases/tag/tag-6.4.2-0

@camAtGitHub did you specify user in Sentinl config in kibana.yml?
```
sentinl:
  settings:
    authentication:
      enabled: true 
      username: 'elastic'
      password: 'password'
```
https://github.com/sirensolutions/sentinl/blob/master/docs/Authentication.md

**Comment by raphaellb2003** [comment]
I also have the very same error on Kibana 6.4.2 (when accessing sentinl tab using the 6.4.2-0 tag): 

```
Error: list watchers : list watcher : Authentication Exception
Error: list watcher : Authentication Exception
    at new SentinlError (https://monitoring.leadfox.co:5601/bundles/sentinl.bundle.js:50:241174)
    at WatcherService._callee4$ (https://monitoring.leadfox.co:5601/bundles/sentinl.bundle.js:50:262601)
    at tryCatch (https://monitoring.leadfox.co:5601/bundles/vendors.bundle.js:43:98500)
    at Generator.invoke [as _invoke] (https://monitoring.leadfox.co:5601/bundles/vendors.bundle.js:43:102382)
    at Generator.prototype.(anonymous function) [as throw] (https://monitoring.leadfox.co:5601/bundles/vendors.bundle.js:43:99623)
    at step (https://monitoring.leadfox.co:5601/bundles/sentinl.bundle.js:50:259127)
    at https://monitoring.leadfox.co:5601/bundles/sentinl.bundle.js:50:259287
```

My kibana config goes as follow : 
```
sentinl:
  es:
    host: 'localhost'
    port: 9200
    protocol: 'https'
  settings:
    authentication:
      enabled: false
      username: 'kibana'
      password: 'REDACTED'
      cert:
        selfsigned: true
    report:
      active: true
```


Fun fact, whether I completely remove this kibana configuration or change the es protocol followed by a restart, the stack trace is identical.


My Search Guard kibana user is on sg_all_access and it's configuration is : 
sg_all_access:
```
  readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    admin_tenant: RW
```

**Comment by O1dOne** [comment]
I can confirm the issue with the latest 6.4.2 beta build (https://github.com/sirensolutions/sentinl/releases/download/tag-6.4.2-0/sentinl-v6.4.2.zip),I have the same errors as the other ReadOnlyRest users here.

But the previous beta, which got removed from releases (used to be available from https://github.com/sirensolutions/sentinl/releases/download/tag-6.4.1-beta-1/sentinl-v6.4.2.zip), works just fine (when I copied it over from the older docker image) with the same configs

**Comment by sergibondarenko** [comment]
@camAtGitHub @lbesuchet 
There is a pkg with fix, please try it https://github.com/sirensolutions/sentinl/releases/download/tag-6.4.2-0/sentinl-v6.4.2.zip

An example of Search Guard and Sentinl configuration.

# 1. Configure Sentinl
```
cd kibana/config
```
## Minimal required config in `kibana.yml`
```
sentinl:
  es:
    protocol: https
  settings:
    authentication:
      enabled: true
      username: sentinl
      password: password
    email:
      active: true
```

# 2. Configure Search Guard
```
cd elasticsearch/plugins/search-guard-6/sgconfig
```
## Create a role in `sg_roles.yml` file
```
sg_sentinl:
  cluster:
    - indices:data/read/scroll
    - indices:admin/template/put
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - MANAGE
        - DATA_ACCESS
        - DELETE
        - INDEX
        - SEARCH
    'watcher*':
      '*':
        - MANAGE
        - DATA_ACCESS
        - DELETE
        - CREATE_INDEX
        - INDEX
        - SEARCH
    '*':
      '*':
        - indices:monitor/stats
        - indices:admin/mappings/get
        - READ
        - SEARCH
```
## Create hash from a clear text password
```
../tools/hash.sh -p password
$2y$12$jgSL8jvZtNuQISaf/hp18ugp23pdpv3ryLHcxpf9lenNyU0uITOb2
```
## Create sentinl user, use the hash and map the role in file `sg_internal_users.yml`
```
sentinl:
  hash: $2y$12$jgSL8jvZtNuQISaf/hp18ugp23pdpv3ryLHcxpf9lenNyU0uITOb2
  roles:
    - sentinl
```
## Apply changes while Elasticsearch is running
```
cd elasticsearch
./plugins/search-guard-6/tools/sgadmin.sh \
   -cd plugins/search-guard-6/sgconfig/ \
   -cacert config/root-ca.pem \
   -cert config/kirk.pem \
   -key config/kirk-key.pem  \
   -nhnv -icl
```

# More
Read [Search Guard](https://docs.search-guard.com/latest/search-guard-sentinl) docs for more details.
