### ISSUE TITLE
Kibana restart error because of report executable_path

### ISSUE THREAD

**Issue by tony-yin** [sirensolutions/sentinl#619]
## Version
es: 6.4.2
kibana: 6.4.2
os: linux centos7
sentinl: 6.4.2.release

## problem 

create one watcher with two actions: email and report,but email can work successflly, report work failed.

1. when config executable_path:

```
sentinl:
  settings:
    email:
      active: true
      #host: 'localhost'
      #ssl: true
      host: 'smtp.163.com'
      user: 'xxx'
      password: 'xxx'
      timeout: 10000
    report:
      active: true
      engine: 'puppeteer' # options: horseman, puppeteer
      executable_path: '/usr/bin/chromium-browser' # path to Chrome v59+ or Chromium v59+
``` 

kibana restart error log:

```
{"type":"error","@timestamp":"2018-11-23T10:49:40Z","tags":["fatal"],"pid":4308,"level":"fatal","error":{"message":"Option \"report.executable_path\" was deprecated. The path is handled automatically!","name":"Error","stack":"Error: Option \"report.executable_path\" was deprecated. The path is handled automatically!\n    at appConfig (/usr/share/kibana/plugins/sentinl/app_config.js:194:54)\n    at config (/usr/share/kibana/plugins/sentinl/index.js:45:14)\n    at getSchema (/usr/share/kibana/src/plugin_discovery/plugin_config/schema.js:47:29)\n    at extendConfigService (/usr/share/kibana/src/plugin_discovery/plugin_config/extend_config_service.js:44:46)\n    at <anonymous>"},"message":"Option \"report.executable_path\" was deprecated. The path is handled automatically!"}
```

2. So remove the executable_path, UI report continue show error

config:
```
sentinl:
  settings:
    email:
      active: true
      #host: 'localhost'
      #ssl: true
      host: 'smtp.163.com'
      user: 'xxx'
      password: 'xxx'
      timeout: 10000
    report:
      active: true
      engine: 'puppeteer' # options: horseman, puppeteer
      #executable_path: '/usr/bin/chromium-browser' # path to Chrome v59+ or Chromium v59+
```
UI error:
![image](https://user-images.githubusercontent.com/18906553/48939736-39be6000-ef50-11e8-8191-1bb22205017b.png)

[Latest doc][1] content is too old so that many config items was changed, it's so hard to config. Please update the doc ,thanks

[1]: https://sentinl.readthedocs.io/en/latest/
