### ISSUE TITLE
Sentinl doesn't send emails with alerts

### ISSUE THREAD

**Issue by Tvlasev** [sirensolutions/sentinl#669]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       |   6.5.4      |
| Elasticsearc |    6.5.4     |
| Server OS    |    Windows 10     |
| Browser      |     Chrome    |

I've installed Sentinl plugin with Search Guard and I send successfully alerts, but I dont recive e-mails for these alerts. 

I followed steps in Troubleshooting section in docs - https://sentinl.readthedocs.io/en/latest/Troubleshoot/. I've installed maildev and run it. 

In my kibana.yml file I've these properties: 

```
sentinl:
  es:
    host: 'localhost'
    port: 9200
    protocol: 'https'
  settings:
    authentication:
      enabled: true 
      username: 'admin'
      password: 'admin'
    email:
      active: true
      #user: admin
      #password: admin
      host: "localhost"
      port: 1025
    report:
      active: true
```

When I execute a watcher with the play button, I got a message "watcher executed" and I recive my alert in the alarms tab, but I dont recive an email in maildev - localhost:1080. 

In the console I got a warning: 

```
log   [16:39:36.028] [info][listening] Server running at http://localhost:5601
  log   [16:39:43.382] [info][Sentinl][watcher_handler] executing
  log   [16:39:43.384] [warning][Sentinl][watcher_handler] Siren federate: "elasticsearch.plugins" is not available when running from kibana: Error: Unknown config key: investigate_core.clusterplugins
  log   [16:39:43.405] [info][Sentinl][watcher_handler] successfully applied condition
  log   [16:39:43.416] [info][Sentinl][watcher_handler] successfuly executed
  log   [16:39:43.473] [info][Sentinl] processing html email
```
Why I've this warning and is it related with mail problem? 

Thanks, any help will be appreciated
