### ISSUE TITLE
Blank reports from Kibana

### ISSUE THREAD

**Issue by goveebee** [sirensolutions/sentinl#709]
#### Versions

| Type         | Version |
|--------------|---------|
| Kibana       | 6.4.2      |
| Elasticsearc |   6.4.2   |
| Server OS    |    Ubuntu   |
| Browser      |     Chrome    |

#### Original Install Method

- [ ] Release pkg link

### Bug Details
I get blank images when I try to create reports of a Kibana Dashboard.
#### Bug Description
All other webpages that I've tried works just fine. Google, Aftonbladet.se and even Elastisearch on the same server as the Kibana-installation. I've tried to add a long delay, to let the page load properly. It seems that there is no delay. I've set the delay to 15s, but I get the mail within 15s from button pushed.

#### Sentinl Setup
```
sentinl:
  es:
    host: 'http://192.168.1.177'
    port: 9200
    protocol: 'http'
    results: 50
    timefield: 'doc.params.@timestamp'
    default_type: 'doc'
    alarm_index: 'watcher_alarms'
    alarm_type: 'sentinl-alarm'
  settings:
    email:
      active: true
      host: 'xxxx.xxxxxx.se'
      user: 'ebro'
      password: 'xxxxxxxx'
      port: 25
      ssl: false
    report:
      active: true
      engine: puppeteer
#      engine: horseman
      puppeteer:
        browser_path: '/usr/bin/google-chrome'
#      horseman:
#       browser_path: /home/adaadmin/Elastic/kibana/plugins/sentinl/phantomjs
```

#### Full Watcher JSON
```
{
  "actions": {
    "report_admin": {
      "throttle_period": "0h0m5s",
      "report": {
        "to": "emil.brolin@apendo.se",
        "from": "info@apendo.se",
        "subject": "Rapport från Hultsfred",
        "priority": "high",
        "body": "Rapport över senaste timmen",
        "snapshot": {
          "res": "1920x1080",
          "url": "http://192.168.1.177:1337/goto/968963c7e3264e9a69b5164f98bf7f77",
          "params": {
            "delay": 5000
          },
          "type": "png",
          "name": "Rapport"
        }
      }
    }
  },
  "input": {
    "search": {
      "request": {
        "index": [],
        "body": {}
      }
    }
  },
  "condition": {
    "script": {
      "script": "payload.hits.total >= 0"
    }
  },
  "trigger": {
    "schedule": {
      "later": "every 1 hours"
    }
  },
  "disable": true,
  "report": true,
  "title": "Rapport Hultsfred",
  "save_payload": false,
  "spy": false,
  "impersonate": false
}
```

#### Screenshots (if relevant)
![image](https://user-images.githubusercontent.com/11960654/55159571-a006f980-5161-11e9-9d7b-b97ce44d936e.png)

#### Errors in Browser Console (if relevant)
```
```
