### ISSUE TITLE
Sentinl GUI not starting (UTC time is {{ utcTime }})

### ISSUE THREAD

**Issue by bellicapelli0** [sirensolutions/sentinl#733]
I'm running Sentinl 6.6.1 on an installation of Kibana 6.7.2. I tested this locally on Arch and Ubuntu with no issue. I'm unable to use any other versions of Kibana and the rest of the ELK stack.
I'm running into issues when running the same exact configuration on a CentOS server 
![aaa](https://user-images.githubusercontent.com/51446689/59034657-c46f0880-886b-11e9-9268-d688acb445e0.png)

The page shown in the picture is completely unresponsive, none of the buttons do anything.
The sentinl section of kibana.yml is as follows:
```

 sentinl:
  settings:
   email:
      active: true
      host: '***'
      port: ***
    report:
      active: true
      engine: horseman # horseman, puppeteer
      puppeteer:
       browser_path: /BIGDATA/kibana-6.7.2-linux-x86_64/data/headless_shell-linux/headless_shell
```

The only sentinl related lines in the stdout logs of kibana are as follows:
```
  log   [13:05:01.771] [info][Sentinl][init] initializing ...
  log   [13:05:01.772] [info][Sentinl][init] Chrome bin found at: /BIGDATA/kibana-6.7.2-linux-x86_64/data/headless_shell-linux/headless_shell
  log   [13:05:01.873] [info][Sentinl][init_indices] checking watcher_alarms-2019.06.06 index ...

```
Please let me know if this issue can be fixed and if there is any more necessary information.
